services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/app/config:/app/config
      - huggingface_cache:/app/.cache/huggingface  # Add this line
    environment:
      - PYTHON_ENV=production
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis-stack:6379
      - CHROMA_URL=http://chroma:8000
      - HF_HOME=/app/.cache/huggingface  # Add this line
      # Remove or comment out TRANSFORMERS_CACHE if present
      # - TRANSFORMERS_CACHE=/app/.cache/huggingface/hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis-stack:
        condition: service_healthy
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_stack_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_stack_data:
  huggingface_cache: