services:
  frontend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHON_ENV=development
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis-stack:6379  # Обновлено на redis-stack
    depends_on:
      redis-stack:
        condition: service_healthy

  redis-stack:
    platform: linux/arm64
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"   # Стандартный порт Redis
      - "8001:8001"   # Переназначенный порт для веб-интерфейса Redis Stack
    volumes:
      - redis_stack_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_stack_data: